name: 📊 GitHub Metrics Grid

on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:

jobs:
  metrics-grid:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-grid.svg
          user: hadimiftahulf
          config_timezone: Asia/Jakarta
          config_twemoji: yes

          config_order: |
            introduction
            languages
            wakatime
            achievements

          plugin_introduction: yes

          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
