name: ⏱️ WakaTime Stats

on:
  schedule: [{ cron: "40 * * * *" }]
  workflow_dispatch:

jobs:
  metrics-wakatime:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-wakatime.svg
          user: hadimiftahulf
          config_timezone: Asia/Jakarta
          config_twemoji: yes

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_limit: 5
          plugin_wakatime_days: 7
